export const ErrorCode = {
  // 400
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_CLIENT: "INVALID_CLIENT",
  INVALID_SCOPE: "INVALID_SCOPE",
  INVALID_GRANT: "INVALID_GRANT",

  // 401
  UNAUTHORIZED: "UNAUTHORIZED",

  // 403
  FORBIDDEN: "FORBIDDEN",

  // 404
  NOT_FOUND: "NOT_FOUND",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // 409
  CONFLICT: "CONFLICT",
  CLIENT_ALREADY_EXISTS: "CLIENT_ALREADY_EXISTS",

  // 429
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  // 500
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCode =
  (typeof ErrorCode)[keyof typeof ErrorCode];